
import java.net.DatagramPacket;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mariomerco
 */
public class jFrm_ChatPrivado extends javax.swing.JFrame {

    /**
     * Creates new form jFrm_ChatPrivado
     */
    public String usuarioInicial;
    public String usuarioDestino;
    private JFrm_Chat formulatioPadre;
    
    public jFrm_ChatPrivado(String usuario1, String usuario2, JFrm_Chat formularioPadre) {
        initComponents();
        this.usuarioDestino = usuario2;
        this.usuarioInicial = usuario1;
        this.formulatioPadre = formularioPadre;
        jLabelUsuarios.setText(usuarioInicial + " - " + usuarioDestino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtPn_conversacion = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneConversacion = new javax.swing.JTextPane();
        jTxtMensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTxtPn_conversacion.setEditable(false);
        jScrollPane2.setViewportView(jTxtPn_conversacion);

        jLabel1.setText("Chat privado");

        jLabelUsuarios.setText("users");

        jTextPaneConversacion.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneConversacion);

        jTxtMensaje.setToolTipText("Escriba mensaje...");
        jTxtMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMensajeActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMensajeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mensaje= jTxtMensaje.getText()+System.getProperty("line.separator");
            String mcompleto = usuarioInicial + ":3:" + jTxtMensaje.getText() + ":" + usuarioDestino;
            byte[] m = mcompleto.getBytes();
            DatagramPacket msalida= new DatagramPacket(m, m.length,this.formulatioPadre.grupo,6789);
            formulatioPadre.sock.send(msalida);
            formatoConversacion(mcompleto, usuarioDestino);
            jTxtMensaje.setText("");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void formatoConversacion(String dato, String userx) throws Exception {
        String[] x = dato.split(":");
        String user = x[0].trim();
        String mensaje = x[2].trim();
        if (!userx.equals(user)) {
            SimpleAttributeSet attrs = new SimpleAttributeSet();
            StyleConstants.setBold(attrs, true);
            this.jTextPaneConversacion.getStyledDocument().insertString(this.jTextPaneConversacion.getStyledDocument().getLength(), user + ": ", attrs);
            StyleConstants.setBold(attrs, false);
            this.jTextPaneConversacion.getStyledDocument().insertString(this.jTextPaneConversacion.getStyledDocument().getLength(), mensaje + System.getProperty("line.separator"), attrs);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrm_ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrm_ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrm_ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrm_ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrm_ChatPrivado("", "", new JFrm_Chat()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextPane jTextPaneConversacion;
    private javax.swing.JTextField jTxtMensaje;
    public javax.swing.JTextPane jTxtPn_conversacion;
    // End of variables declaration//GEN-END:variables
}
